chore: Add ncc and build dist/
Signed-off-by: Oğuzhan Durgun <oguzhandurgun95@gmail.com>

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -29,3 +29,17 @@ jobs:
       - name: Lint
         run: |
           pnpm run lint
+      
+      - name: Build
+        run: |
+          pnpm run build
+      
+      - name: Check repo status
+        run: |
+          repo_status=$(git status --porcelain)
+          if [[ ! -z "${repo_status}" ]]; then
+            echo "::error::Uncommitted changes detected"
+            echo "${repo_status}"
+            git status -vv
+            exit 1
+          fi
